function ChangeLang(str){
    $("[i18n]").i18n({
        defaultLang: str,
        filePath: "../script/i18n/",
        filePrefix: "i18n_",
        fileSuffix: "",
        forever: true,
        callback: function() {
            // 切换语言成功后的返回
        }
    });
}
var cn = {
    '手机号长度必须为11位':'手机号长度必须为11位',
    '请输入验证码':'请输入验证码',
    '后重试':'后重试',
    '获取验证码':'获取验证码',
    '暂时无法获取验证码':'暂时无法获取验证码',
    '输入手机号':'输入手机号',
    '输入验证码':'输入验证码',
    '验证码发送成功':'验证码发送成功',
    '验证码获取失败':'验证码获取失败',
    '请先获取验证码':'请先获取验证码',
    '验证码无效':'验证码无效',
    '验证码已过期':'验证码已过期',
    '再次按下返回键则退出app':'再次按下返回键则退出app',
    '努力加载中':'努力加载中',
    '请稍等':'请稍等',
    '请打开【WIFI】和【位置信息】':'请打开【WIFI】和【位置信息】',
    //main页面
    '卡伦特冲奶机':'冲奶机',
    '美赞臣经典版安儿宝A':'冲奶机',
    '提示':'(1-3岁)幼儿配方奶粉-单次喂18g/100ml',
    '单次喂奶':'(1-3岁)幼儿配方奶粉-单次喂',
    '奶量':'泡奶水量ß',
    '奶瓶放置': '奶瓶放置',
    '奶盒放置':'奶盒放置',
    '是否有水':'进水等待',
    '温度检测':'温度检测',
    '水箱放置':'水箱放置',
    '混合仓':'混合仓',
    '冲奶':'冲奶',
    '冲奶中':'冲奶中',
    '加热中':'加热中',
    '排水中':'排水中',
    '再次按下强制中断泡奶':'再次按下强制中断泡奶',
    '当前状态无法进行操作':'当前状态无法进行操作',
    '设备未就绪':'设备未就绪',
    '请检查设备':'请检查设备',
    '水温异常':'水温异常',
    '奶瓶放置异常':'奶瓶放置异常',
    '粉盒放置异常':'粉盒放置异常/奶粉量不足',
    '水箱放置异常':'水箱放置异常',
    '混合仓放置异常':'混合仓放置异常',
    '冷却仓水量过低':'冷却仓水量过低',
    '设备未启动':'设备未启动',
    '冷却仓水温过高':'冷却仓水温过高',
    '流速不正常':'流速不正常',
    '泡奶温度过高或过低':'泡奶温度过高或过低',
    '奶粉量不正常':'奶粉量不正常',
    '泡奶失败':'泡奶失败',
    '对准条形码':'对准条形码/二维码，即可自动扫描',
    '摄像头访问失败':'摄像头访问失败',
    '相册访问失败':'相册访问失败',
    '宝宝':'宝宝',
    '今日喝奶量':'  今日喝奶量',
    '正在上传图片':'正在上传图片',
    '请稍后':'请稍后',
    '保存成功':'保存成功',
    '奶粉':"奶粉",
    '请输入奶粉名称':'请输入奶粉名称',
    '正在配置':'正在配置',
    '配置失败':'配置失败',
    '请输入WiFi密码':'请输入WiFi密码',
    '水箱缺水':'水箱缺水',
    '请打开【WIFI】':'请打开【WIFI】',
    '设备网络配置不正确':'设备网络配置不正确,请重新添加网络',
    '再次按下退出登录':'再次按下退出登录',
    '再次按下解除设备绑定':'再次按下解除设备绑定',
    '冲调温度':'冲调温度',
    "菜单":"说明",

    "wifi2.4":"请确保连接的网络为2.4ghz网络",
    "bleConfirm":"请确保您的设备支持蓝牙连接功能，否则将无法使用蓝牙进行连接!",
    "wifi错误":"wifi错误",
    "请将wifi切换为XPG-GAgent-xxx":"请将wifi切换为XPG-GAgent-xxx",
    "请输入家庭wifi密码":"请输入家庭wifi密码",
    "请输入家庭wifi名称":"请输入家庭wifi名称",
    "奶粉设置":"奶粉设置",

    "奶粉配比":"奶粉配比:",
    "段":"段",
    "奶粉段位":"奶粉段位:",
    "奶粉名称":"奶粉名称:",
    "登陆":"登录",
    "获取验证码":"获取验证码",
    "删除":"删除",
    "修改":"修改",

    "是否解绑设备":"是否解绑设备",
    "按下确定将会解绑设备":"按下确定将会解绑设备",
    "确定":"确定",
    "取消":"取消",

    "设置":"设置",
    "温水":"温水",

    "区号":"区号",
    "手机":"手机",
    "验证码":"验证码",
    "隐私政策":"隐私政策",
    
    "PrivacyPolicy":"隐私政策",
    "Privacy1":"我们将冲奶机应用程序构建为免费应用程序。本服务免费提供，拟按原样使用。",
    "Privacy2":"如果有人决定使用我们的服务，此页面用于通知访问者有关我们收集、使用和披露个人信息的政策。",
    "Privacy3":"如果您选择使用我们的服务，那么您同意收集和使用与本政策有关的信息。我们收集的个人信息用于提供和改进服务。我们不会使用或与任何人共享您的信息，除非本隐私政策中有说明。",
    "Privacy4":"本隐私政策中使用的术语与我们条款和条件中使用的术语具有相同的含义，可在冲奶机访问,除非本隐私政策另有规定。",
    "Privacy5":"信息收集与利用",
    "Privacy6":"为了获得更好的体验，在使用我们的服务时，我们可能会要求您向我们提供某些个人身份信息. 我们要求的信息将由我们保留，并按照本隐私政策中的说明使用。",
    "Privacy7":"该应用程序确实使用了第三方服务，这些服务可能会收集用于识别您身份的信息。",
    "Privacy8":"链接到应用程序使用的第三方服务提供商的隐私政策",
    "Privacy9":"谷歌商店服务",
    "Privacy10":"日志数据",
    "Privacy11":"我们想通知您，每当您使用我们的服务时，如果应用程序出现错误，我们会（通过第三方产品）在您的手机上收集数据和信息，称为日志数据。此日志数据可能包括您的设备Internet协议（“IP”）地址、设备名称、操作系统版本、使用我们的服务时应用程序的配置、使用服务的时间和日期以及其他统计信息。",
    "Privacy12":"缓存",
    "Privacy13":"缓存是包含少量数据的文件，通常用作匿名唯一标识符。它们从您访问的网站发送到您的浏览器，并存储在设备的内部内存中。",
    "Privacy14":"此服务不显式使用这些“cookies”。然而，应用程序可能会使用第三方代码和使用“cookies”的库来收集信息和改进服务。您可以选择接受或拒绝这些cookie，并知道cookie何时被发送到您的设备。如果您选择拒绝我们的cookies，您可能无法使用此服务的某些部分。",
    "Privacy15":"服务提供商",
    "Privacy16":"由于以下原因，我们可能雇佣第三方公司和个人：",
    "Privacy17":"方便我们的服务；",
    "Privacy18":"代表我们提供服务；",
    "Privacy19":"提供与服务有关的服务；或",
    "Privacy20":"帮助我们分析如何使用我们的服务。",
    "Privacy21":"我们想通知此服务的用户，这些第三方可以访问您的个人信息。原因是代表我们执行分配给他们的任务。但是，他们有义务不披露或将信息用于任何其他目的。",
    "Privacy22":"安全",
    "Privacy23":"我们重视您的信任，为我们提供您的个人信息，因此我们正在努力使用商业上可接受的手段来保护它。但请记住，任何通过互联网的传输方法或电子存储方法都不是100%安全可靠的，我们不能保证其绝对安全。",
    "Privacy24":"指向其他网站的链接",
    "Privacy25":"此服务可能包含指向其他网站的链接。如果您单击第三方链接，您将被定向到该站点。请注意，这些外部站点不是由我们操作的。因此，我们强烈建议您审查这些网站的隐私政策。我们对任何第三方网站或服务的内容、隐私政策或做法没有控制权，也不承担任何责任。",
    "Privacy26":"儿童隐私",
    "Privacy27":"这些服务不针对13岁以下的任何人。我们不会故意收集13岁以下儿童的个人识别信息。如果我们发现13岁以下儿童向我们提供了个人信息，我们会立即从服务器上删除此信息。如果您是家长或监护人，并且您知道您的孩子向我们提供了个人信息，请与我们联系，以便我们能够采取必要的行动。",
    "Privacy28":"此隐私政策的更改",
    "Privacy29":"我们可能会不时更新我们的隐私政策。因此，建议您定期查看本页的任何更改。如有任何更改，我们会在本页张贴新的隐私政策。",
    "agree":"同意",
    "开启连接":"开启连接",
    "不在数据库需手动设置":"不在数据库需手动设置"
    
}
var en = {
    '手机号长度必须为11位':'Cell phone number length must be 11 digits',
    '请输入验证码':'Please enter the verification code',
    '后重试':'Retry after',
    '获取验证码':'Get code',
    '暂时无法获取验证码':'Temporarily unable to obtain captcha',
    '输入手机号':'Enter your phone number',
    '输入验证码':'code is needed',
    '验证码发送成功':'The verification code was sent successfully',
    '验证码获取失败':'Captcha acquisition failed',
    '请先获取验证码':'Please get the verification code first',
    '验证码无效':'Captcha code',
    '验证码已过期':'The verification code has expired',
    '再次按下返回键则退出app':'Press the return key again to exit the app',
    '努力加载中':'Under hard load',
    '请稍等':'Just a moment, please',
    '请打开【WIFI】和【位置信息】':'Please turn on 【WIFI】 and 【location】 information',
    //main
    '卡伦特冲奶机':'MILK',
    '美赞臣经典版安儿宝A':'MILK',
    '提示':'(1-3 years old) 18g/100ml',
    '奶量':'milk',
    '奶瓶放置': 'Bottle placed',
    '奶盒放置':'Milk box',
    '是否有水':'Has water',
    '温度检测':'Temperature',
    '水箱放置':'Tank placed',
    '混合仓':'Mixing silo',
    '冲奶':'Blunt',
    '冲奶中':'Blunting',
    '加热中':'heating',
    '排水中':'drainage',
    '再次按下强制中断泡奶':'Press again to force the milk to stop',
    '当前状态无法进行操作':'The current state cannot be operated on',
    '设备未就绪':'Equipment not ready',
    '请检查设备':'Please check the equipment',
    '水温异常':'The water temperature anomaly',
    '奶瓶放置异常':'Abnormal bottle placement',
    '粉盒放置异常':'Cartridge placement is abnormal/Insufficient milk powder',
    '水箱放置异常':'Tank placement anomaly',
    '混合仓放置异常':'The mixing bin is placed abnormally',
    '冷却仓水量过低':'The cooling tank is too low',
    '设备未启动':'Device not started',
    '冷却仓水温过高':'The temperature of the cooling chamber is too high',
    '流速不正常':'Abnormal flow rate',
    '泡奶温度过高或过低':'Too hot or too cold',
    '奶粉量不正常':'The amount of milk powder is abnormal',
    '泡奶失败':'Bubble milk failure',
    '对准条形码':'Aim at the bar code/qr code, it can be automatically scanned',
    '摄像头访问失败':'Camera access failed',
    '相册访问失败':'Album access failed',
    '宝宝':'Baby',
    '今日喝奶量':'  Drink enough milk today',
    '正在上传图片':'Uploading pictures',
    '请稍后':'Please later',
    '保存成功':'Save success',
    '奶粉':"Milk powder ",
    '请输入奶粉名称':'Please enter milk powder' ,
    '正在配置':'Is the configuration',
    '配置失败':'Configuration failed',
    '请输入WiFi密码':'WiFi password',
    '水箱缺水':'water shortage',
    '请打开【WIFI】':'Please open the WIFI',  
    '设备网络配置不正确':'The device network configuration is not correct, please add the network again',
    '再次按下退出登录':'Press log out again',
    '再次按下解除设备绑定':'Press again to unbind the device',
    '单次喂奶':'(1-3 years old) feeding',
    '冲调温度':'temperature',
    "菜单":"Explanation",

    "wifi2.4":"Please make sure you are connected to a 2.4GHz network",
    "bleConfirm":"Please ensure that your device supports Bluetooth connection function, otherwise you will not be able to connect using Bluetooth!",
    "wifi错误":"wifi error",
    "请将wifi切换为XPG-GAgent-xxx":"Please switch wifi to XPG-GAgent-xxx",
    "请输入家庭wifi密码":"Please enter home wifi password",
    "请输入家庭wifi名称":"Please enter the home wifi name",
    "奶粉设置":"Milk settings",

    "奶粉配比":"Milk powder ratio:",
    "段":"Rank",
    "奶粉段位":"Milk powder rank:",
    "奶粉名称":"Milk powder name:",
    "登陆":"Sign in",
    "获取验证码":"get code",
    "删除":"delete",
    "修改":"modify",

    "是否解绑设备":"Whether to unbind the device",
    "按下确定将会解绑设备":"Pressing OK will unbind the device",
    "确定":"OK",
    "取消":"Cancel",

    "设置":"Setting",
    "温水":"Hot",

    "区号":"Area",
    "手机":"Phone",
    "验证码":"Code",
    "隐私政策":"Privacy Policy",

    "PrivacyPolicy":"Privacy Policy",
    "Privacy1":"We built the app as a free app. This service is provided at no cost and is intended for use as is.",
    "Privacy2":"This page is used to inform visitors regarding ourpolicies with the collection, use, and disclosure of PersonalInformation if anyone decided to use our Service.",
    "Privacy3":"If you choose to use our Service, then you agree tothe collection and use of information in relation to thispolicy. The Personal Information that we collect isused for providing and improving the Service. We will not use or share your information withanyone except as described in this Privacy Policy.",
    "Privacy4":"The terms used in this Privacy Policy have the same meaningsas in our Terms and Conditions, which is accessible at the app unless otherwise defined in this Privacy Policy.",
    "Privacy5":"Information Collection and Use",
    "Privacy6":"For a better experience, while using our service, we may require you to provide us with certain personally identifiable information. The information thatwe request will be retained by us and used as described in this privacy policy.",
    "Privacy7":"The app does use third party services that may collect information used to identify you.",
    "Privacy8":"Link to privacy policy of third party service providers used by the app",
    "Privacy9":"Google Play Services",
    "Privacy10":"Log Data",
    "Privacy11":"We want to inform you that whenever you use our Service, in a case of an error in the app we collect data and information (through third party products) on your phone called Log Data. This Log Data may include information such as your device Internet Protocol (“IP”) address, device name, operating system version, the configuration of the app when utilizing our Service, the time and date of your use of the Service, and other statistics.",
    "Privacy12":"Cookies",
    "Privacy13":"Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device's internal memory.",
    "Privacy14":"This Service does not use these “cookies” explicitly. However, the app may use third party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.",
    "Privacy15":"Service Providers",
    "Privacy16":"We may employ third-party companies and individuals due to the following reasons:",
    "Privacy17":"To facilitate our Service;",
    "Privacy18":"To provide the Service on our behalf;",
    "Privacy19":"To perform Service-related services; or",
    "Privacy20":"To assist us in analyzing how our Service is used.",
    "Privacy21":"We want to inform users of this Service that these third parties have access to your Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.",
    "Privacy22":"Security",
    "Privacy23":"We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.",
    "Privacy24":"Links to Other Sites",
    "Privacy25":"This Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by us. Therefore, we strongly advise you to review the Privacy Policy of these websites. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.",
    "Privacy26":"Children’s Privacy",
    "Privacy27":"These Services do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13. In the case we discover that a child under 13 has provided us with personal information, we immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do necessary actions.",
    "Privacy28":"Changes to This Privacy Policy",
    "Privacy29":" We may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page.",
    "agree":"I Agree",
    "开启连接":"connection",
    "不在数据库需手动设置":"If the database is not used, you need to manually set this parameter"
}
var ko = {
    '手机号长度必须为11位':'핸드폰 번호의 길이는 반드시 11자리여야 한다',
    '请输入验证码':'인증 번호를 입력하십시오',
    '后重试':'재시도',
    '获取验证码':'인증코드 가져오기',
    '暂时无法获取验证码':'현재 인증할 수 없는 코드',
    '输入手机号':'휴대폰 번호 입력',
    '输入验证码':'인증 코드 입력',
    '验证码发送成功':'인증코드 전송에 성공했습니다.',
    '验证码获取失败':'인증코드 가져오기 실패',
    '请先获取验证码':'먼저 확인 코드 가져오기',
    '验证码无效':'유효하지 않은 인증코드',
    '验证码已过期':'유효성 검사 코드',
    '再次按下返回键则退出app':'되돌아가기 버튼을 다시 누르면 app를 종료합니다',
    '努力加载中':'로딩 중',
    '请稍等':'잠시만요.',
    '请打开【WIFI】和【位置信息】':'[WIFI] 및 [위치 정보]를 켜주세요.',
    //main页面
    '卡伦特冲奶机':'마이 콜렛',
    '美赞臣经典版安儿宝A':'콜렛 자동분유제조기',
    '提示':'분유 18g/ 물양 100ml',
    '奶量':'물양 조절',
    '奶瓶放置': '젖병',
    '奶盒放置':'분유통',
    '是否有水':'물 부족',
    '温度检测':'고온 주의',
    '水箱放置':'물탱크',
    '混合仓':'깔때기',
    '冲奶':'조유',
    '冲奶中':'조유중',
    '加热中':'뜨거 운',
    '排水中':'배수',
    '再次按下强制中断泡奶':'강제로 중단한 거품 크림을 다시 누르다',
    '当前状态无法进行操作':'현재 상태를 조정할 수 없습니다.',
    '设备未就绪':'기기가 연결되지 않았습니다.',
    '请检查设备':'기기를 확인해 주세요.',
    '水温异常':'수온이 너무 높습니다.',
    '奶瓶放置异常':'젖병을 받침대에 올려주세요.',
    '粉盒放置异常':'콤팩트 이상/분유량이 부족하다',
    '水箱放置异常':'물탱크를 이상 방치하다.',
    '混合仓放置异常':'혼합창고 설치 이상',
    '冷却仓水量过低':'냉각 창고의 수량이 너무 적다.',
    '设备未启动':'장치가 시작되지 않았습니다',
    '冷却仓水温过高':'냉각기가 과열되었습니다.',
    '流速不正常':'유속이 정상적이지 않다.',
    '泡奶温度过高或过低':'우유 담그는 온도가 지나치게 높거나 지나치게 낮다.',
    '奶粉量不正常':'분유의 양이 정상적이지 않다.',
    '泡奶失败':'우유 담그는 데 실패하다',
    '对准条形码':'바코드/2d 코드를 맞추면 바로 자동으로 스캔할 수 있다',
    '摄像头访问失败':'카메라 접근 실패',
    '相册访问失败':'앨범 접근 실패',
    '宝宝':'아기',
    '今日喝奶量':'  오늘의 분유량',
    '正在上传图片':'그림 올리는 중',
    '请稍后':'잠시만 기다려주세요',
    '保存成功':'저장 성공',
    '奶粉':"분유",
    '请输入奶粉名称':'분유 이름을 입력하십시오.',
    '正在配置':'연결중',
    '配置失败':'설정 실패',
    '请输入WiFi密码':'WiFi 비밀번호를 입력하십시오.',
    '水箱缺水':'냉각수 부족',
    '请打开【WIFI】':'WIFI를 켜주세요.',
    '设备网络配置不正确':'장치 네트워크 설정이 잘못되었습니다. 네트워크를 다시 추가하십시오',
    '再次按下退出登录':'로그아웃 다시 누르기',
    '再次按下解除设备绑定':'다시 장치 바인딩 해제하기',
    '单次喂奶':'(1-3 세) 영아 용 조제 분유',
    '冲调温度':'온도 설정',
    "菜单":"설명",

    "wifi2.4":"2.4GHz Wi-Fi 네트워크로 연결해 주시기 바랍니다.",
    "bleConfirm":"장치가 블루투스 연결 기능을 지원하는지 확인하십시오. 그렇지 않으면 블루투스로 연결할 수 없습니다.",
    "wifi错误":"Wi-Fi 오류",
    "请将wifi切换为XPG-GAgent-xxx":"Wi-Fi를 XPG-GAgent-xxx로 전환하세요.",
    "请输入家庭wifi密码":"홈 와이파이 비밀번호를 입력하세요",
    "请输入家庭wifi名称":"홈 와이파이 이름을 입력하세요",

    "奶粉设置":"분유 설정",

    "奶粉配比":"분유 비율:",
    "段":"단계",
    "奶粉段位":"분유 단계:",
    "奶粉名称":"분유 명:",
    "登陆":"로그인",
    "获取验证码":"인증 코드",
    "删除":"삭제",
    "修改":"수정",
    
    "是否解绑设备":"장치 바인딩 해제 여부",
    "按下确定将会解绑设备":"확인을 누르면 장치의 바인딩이 해제됩니다.",
    "确定":"확인",
    "取消":"취소",

    "设置":"설정",
    "温水":"온수추출",

    "区号":"국가 코드",
    "手机":"휴대폰 번호",
    "验证码":"인증 코드",
    "隐私政策":" 개인정보 정책",
    
    "PrivacyPolicy":"프라이버시 정책",
    "Privacy1":"우 리 는 무료 응용 프로그램 을 만 들 었 다.본 서 비 스 는 무료 로 제공 합 니 다, 그대로 사용 된다.",
    "Privacy2":"만약 에 저희 서 비 스 를 사용 하기 로 결정 하면 이 페이지 는 방문 자 에 게 저희 가 개인 정 보 를 수집, 사용, 공개 하 는 정책 을 알 리 는 데 사 용 됩 니 다.",
    "Privacy3":"만약 에 귀하 가 저희 서 비 스 를 선택 하 시 면 귀 하 는 본 정책 과 관련 된 정 보 를 수집 하고 사용 하 는 것 에 동의 합 니 다.저희 가 수집 한 개인 정 보 는 서 비 스 를 제공 하고 개선 하 는 데 사 용 됩 니 다.저 희 는 본 프라이버시 정책 에 설명 이 있 는 경 우 를 제외 하고 그 누구 와 도 귀하 의 정 보 를 사용 하거나 공유 하지 않 습 니 다.",
    "Privacy4":"본 프라이버시 정책 에서 사용 하 는 용 어 는 우리 의 조항 과 조건 에서 사용 하 는 용어 와 같은 의 미 를 가지 고 있 으 므 로  에서 방문 할 수 있 습 니 다.본 프라이버시 정책 에 따로 규정 이 있 는 경 우 를 제외 하고 응용 프로그램 에 접근 할 수 있 습 니 다.",
    "Privacy5":"정보 수집 과 이용",
    "Privacy6":"더 좋 은 경험 을 얻 기 위해 저희 서 비 스 를 사용 할 때 저 희 는 귀하 께 개인 신분 정 보 를 제공 하 라 고 요구 할 수 있 습 니 다.저희 가 요구 하 는 정 보 는 저희 가 보류 하고 본 프라이버시 정책 의 설명 에 따라 사용 할 것 입 니 다.",
    "Privacy7":"이 앱 은 제3자 서 비 스 를 사 용 했 기 때문에 이러한 서 비 스 는 귀하 의 신분 을 식별 하 는 정 보 를 수집 할 수 있 습 니 다.",
    "Privacy8":"응용 프로그램 에 연 결 된 제3자 서비스 제공 업 체 의 프라이버시 정책",
    "Privacy9":"구 글 게임 서비스",
    "Privacy10":"로그 데이터",
    "Privacy11":"저 희 는 귀하 가 저희 서 비 스 를 사용 할 때마다 프로그램 이 잘못 되면 저 희 는 귀하 의 핸드폰 에서 데이터 와 정 보 를 수집 하여 로그 데이터 라 고 부 르 는 것 을 알려 드 리 고 싶 습 니 다.이 로그 데 이 터 는 귀하 의 기기 인터넷 프로 토 콜 (IP) 주소, 장치 이름, 운영 체제 버 전, 저희 서 비 스 를 사용 할 때 프로그램의 설정, 서 비 스 를 사용 하 는 시간 과 날짜 및 기타 통계 정 보 를 포함 할 수 있 습 니 다.",
    "Privacy12":"Cookies",
    "Privacy13":"Cookie 는 소량의 데 이 터 를 포함 하 는 파일 로 익명 의 유일한 식별 자로 사 용 됩 니 다.그들 은 귀하 가 방문 한 사이트 에서 귀하 의 브 라 우 저 로 보 내 고 장치 의 내부 메모리 에 저장 합 니 다.",
    "Privacy14":"이 서 비 스 는 이러한 cookies 를 명시 적 으로 사용 하지 않 습 니 다.그러나 응용 프로그램 은 제3자 코드 와 'cookies' 라 이브 러 리 를 사용 하여 정 보 를 수집 하고 서 비 스 를 개선 할 수 있 습 니 다.귀 하 는 이러한 쿠키 를 받 아들 이거 나 거부 할 수 있 고 쿠키 가 언제 귀하 의 장치 에 전송 되 는 지 알 수 있 습 니 다.만약 에 귀하 가 저희 의 cookies 를 거절 하면 귀 하 는 이 서비스의 일부 부분 을 사용 할 수 없습니다.",
    "Privacy15":"서비스 공급 자",
    "Privacy16":"다음 과 같은 이유 로 저 희 는 제3자 회사 와 개인 을 고용 할 수 있 습 니 다:",
    "Privacy17":"저희 서비스 편 의 를 위해 서;",
    "Privacy18":"저 희 를 대표 하여 서 비 스 를 제공 합 니 다.",
    "Privacy19":"서비스 와 관련 된 서 비 스 를 제공한다.혹시",
    "Privacy20":"우리 가 우리 의 서 비 스 를 어떻게 사용 하 는 지 분석 하 는 것 을 돕다.",
    "Privacy21":"저 희 는 이 서비스의 사용자 에 게 이 제3자 가 귀하 의 개인 정 보 를 방문 할 수 있다 는 것 을 알려 드 리 고 싶 습 니 다.우 리 를 대표 해서 그들 에 게 주어진 임 무 를 수행 하기 때문이다.그러나 그들 은 정 보 를 공개 하지 않 거나 다른 목적 에 사용 할 의무 가 있다.",
    "Privacy22":"안전 하 다.",
    "Privacy23":"저 희 는 귀하 의 신뢰 를 중시 하고 저희 에 게 귀하 의 개인 정 보 를 제공 하기 때문에 저 희 는 상업 적 으로 받 아들 일 수 있 는 수단 으로 보호 하기 위해 노력 하고 있 습 니 다.그러나 인터넷 을 통 해 전송 하 는 방법 이나 전자 저장 방법 은 모두 100% 안전 하고 믿 을 수 있 는 것 이 아니 므 로 우 리 는 절대적 인 안전 을 보장 할 수 없다 는 것 을 기억 하 십시오.",
    "Privacy24":"다른 사 이 트 를 가리 키 는 링크",
    "Privacy25":"이 서 비 스 는 다른 사 이 트 를 가리 키 는 링크 를 포함 할 수 있 습 니 다.만약 에 제3자 링크 를 클릭 하면 이 사이트 로 지정 합 니 다.이 외부 사이트 들 은 우리 가 조작 하 는 것 이 아 닙 니 다.그러므로 저 희 는 귀하 께 이러한 사이트 의 프라이버시 정책 을 심사 하 는 것 을 강력 히 권장 합 니 다.저 희 는 그 어떠한 제3자 사이트 나 서비스의 내용, 프라이버시 정책 이나 방법 에 대해 통제 권 이 없고 그 어떠한 책임 도 지지 않 습 니 다.",
    "Privacy26":"어린이 프라이버시",
    "Privacy27":"이러한 서 비 스 는 13 세 이하 의 누구 에 게 도 적용 되 지 않 습 니 다. 13 세 이하 의 어린 이 를 위 한 개인 식별 정 보 를 의도 적 으로 수집 하지 않 습 니 다. 13 세 이하 의 어린 이 를 발견 하면 서버 에서 바로 삭 제 됩 니 다.만약 에 귀하 가 학부 모 나 보호자 이 고 귀하 의 아이 가 저희 에 게 개인 정 보 를 제공 한 것 을 알 게 된다 면 저희 가 필요 한 행동 을 할 수 있 도록 연락 주 십시오.",
    "Privacy28":"이 프라이버시 정책 의 변경",
    "Privacy29":"우 리 는 때때로 우리 의 프라이버시 정책 을 갱신 할 수 있다.따라서 이 페이지 의 변경 사항 을 정기 적 으로 확인 하 는 것 을 권장 합 니 다.변경 사항 이 있 으 면,우 리 는 이 페이지 에 새로운 프라이버시 정책 을 게시 할 것 입 니 다.",
    "agree":"동의 하 다.",
    "开启连接":"논리곱",
    "不在数据库需手动设置":"데이터베이스에 없는 항목을 수동으로 설정합니다"
}
function getTranslate(str){
    // 获取翻译后的文字
    var language = $api.getStorage('language')
    var callback = '语言转换错误'
    // 默认语言为中文
    switch(language) {
        case 'cn':
           callback = cn[str]
           break;
        case 'en':
            callback = en[str]
           break;
        case 'ko':
            callback = ko[str]
           break;
        default:
            callback = cn[str]
    } 
    return callback
}